# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
files: ^formatting/

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-ast
      - id: check-toml
      - id: check-yaml
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: local
    hooks:
    - id: black
      name: formatting with black
      entry: black --line-length=88
      language: system
      types: [python]

    - id: autoflake
      name: removes unused imports/variables with autoflake
      entry: autoflake --in-place --remove-unused-variables
      language: system
      types: [python]

    - id: isort
      name: sort imports with isort
      entry: isort --overwrite-in-place
      language: system
      types: [python]
